### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by ghost** [williamshoops96/Chip-Emul8#1]
I am very new to C development as well as this being my first Issue on github, so be patient with me if I did anything wrong.

I had to install the libraries `libsdl2-mixer-dev` and `freeglut3-dev`

_I had to make a minor change to cpu.c, changing from this:
`#include <SDL2_mixer/SDL_mixer.h>`
to this:
`#include <SDL2/SDL_mixer.h>`_
As well as a minor change to ch8.c, changing this:
`#include <GLUT/glut.h>` to `#include <GL/glut.h>`

And this is the command I used to compile (I'm not yet familiar enough with make):
`gcc ch8.c cpu.c -std=c99 -lGLU -lGL -lglut -lSDL2_mixer -o ch8`

I was hoping to build it without any changes to source, but I couldn't see any other way.
Does it still build on Mac with that minor change? or if it doesn't, is there a way to include both statements?

**Comment by shnupta** [comment]
@EmanP Hi there, no problem:)

So, you don't actually need the `SDL_mixer` library right now as I haven't implemented sound, but that means you'd have to delete all references in the source to SDL_mixer (I don't think there are that many btw). Also, as far as I know, the GLUT library should work like you've done there. I'll boot up a version of linux and try to get it running when I can and I'll let you know what I did.

I'm pretty busy at the moment but I'll let you know when I'm done:)

EDIT:
Could you post the results you got when building so I could take a look please?

**Comment by shnupta** [comment]
Just trying to build now.

**Comment by shnupta** [comment]
So I'm building fine but getting a segmentation fault when trying to run...

Checkout the linux branch I've just pushed.

**Comment by ghost** [comment]
~~The segfault I believe is because of the lack of the implementation of sound.~~ This is wrong, as it still segfaults even in the new branch with SDL_mixer references removed.

You can run it in gdb by typing in:

`gdb`
`file ./ch8`
`run ./c8games/nameofgame`
And this somehow represses the crash.

About to build the new one now.

**Comment by ghost** [comment]
For some reason it doesn't build with the Makefile (just like before), but it builds with the gcc command in the original post.
I modified the makefile to include `std=c99`, to prevent the errors pertaining to 

>  ‘for’ loop initial declarations are only allowed in C99 mode

Running `make build` generates the cc command `cc -Wall -g -std=c99 -lGLU -lGL -lglut     ch8.c cpu.c   -o ch8`, which fails, seemingly because it has undefined references to  GL and glut.

But reordering the command to type `cc -Wall -g ch8.c cpu.c -std=c99 -lGLU -lGL -lglut        -o ch8` builds fine.

I'm not sure how to express this in Make.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/4078981/16640272/9d8e09e2-43ee-11e6-960b-2bc26337674d.png)

This is proof of it running when in gdb after having built correctly. Interestingly, running merlin.c8 freezes and gives
`[ERROR] (function:decode_opcode opcodes.h:35: errno: Resource temporarily unavailable) Unknown opcode: 0` on an infinite loop.

**Comment by shnupta** [comment]
@EmanP So sorry for not getting back to you. Glad to see you have got it working! Is merlin.c8 the only game which does this? If you can, make a pull request and I'll merge it with the linux branch and change the Makefile:)

**Comment by ghost** [comment]
The pull request has been made at #2. Merging that should fix this issue.
